apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
    - host: www.agrofest-eventos-reserva.lat
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: agrofest-server-srv
                port:
                  number: 3000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: agrofest-client-srv
                port:
                  number: 5173
